### ISSUE TITLE
configshell_fb not found

### ISSUE THREAD

**Issue by ich777** [open-iscsi/configshell-fb#59]
Hello,

got a little problem compiling configshell-fb from the source for slackware

I did this steps:

1. Compile targetcli-fb
2. Compile rtslib-fb
3. Compile configshell-fb with this steps:
         python3 setup.py build
         python3 setup.py install --prefix=/usr

After that I get the following if I type in `targetcli status`:

```
Traceback (most recent call last):
File "/usr/bin/targetcli", line 4, in <module>
__import__('pkg_resources').run_script('targetcli-fb==2.1.53', 'targetcli')
File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 667, in run_script
self.require(requires)[0].run_script(script_name, ns)
File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1471, in run_script
exec(script_code, namespace, namespace)
File "/usr/lib/python3.8/site-packages/targetcli_fb-2.1.53-py3.8.egg/EGG-INFO/scripts/targetcli", line 24, in <module>
File "<frozen zipimport>", line 259, in load_module
File "/usr/lib/python3.8/site-packages/targetcli_fb-2.1.53-py3.8.egg/targetcli/__init__.py", line 18, in <module>
File "<frozen zipimport>", line 259, in load_module
File "/usr/lib/python3.8/site-packages/targetcli_fb-2.1.53-py3.8.egg/targetcli/ui_root.py", line 29, in <module>
ModuleNotFoundError: No module named 'configshell_fb'
```

This is my folder structure inside site-packages:
![Bildschirmfoto_2020-07-28_16-47-50](https://user-images.githubusercontent.com/28066518/88681943-639b3300-d0f2-11ea-97c6-fff916b4881f.png)

Am I missing something?

Regards

**Comment by ich777** [comment]
My fault, solved...
