### ISSUE TITLE
Execute targetcli commands concurrently raise EOFError

### ISSUE THREAD

**Issue by zoumingzhe** [open-iscsi/configshell-fb#60]
Hello, the following error occur intermittently when 10 targetcli commands are executed concurrently.
```
Traceback (most recent call last):
  File "/usr/bin/targetcli", line 329, in <module>
    main()
  File "/usr/bin/targetcli", line 254, in main
    shell = TargetCLI(getenv("TARGETCLI_HOME", '~/.targetcli'))
  File "/usr/lib/python2.7/site-packages/configshell_fb/shell.py", line 176, in __init__
    self.prefs.load()
  File "/usr/lib/python2.7/site-packages/configshell_fb/prefs.py", line 150, in load
    self._prefs = six.moves.cPickle.load(fsock)
EOFError
```

**Comment by nijave** [comment]
Ran into this with democratic-csi (concurrent iscsi ops over ssh)
