### ISSUE TITLE
'NoneType' object has no attribute 'Console'

### ISSUE THREAD

**Issue by TaylorTrz** [open-iscsi/configshell-fb#63]
## Description
I tried to build iSCSI Gateway demo environment, but configshell returns 'NoneType' object has no attribute 'Console'.

Then I checked the code of configshell, and it look likes this...

```python
if console is None:
    console = console.Console()
    self.con = console
```

## Logs & Configs

```python
Traceback (most recent call last):
  File "/usr/bin/gwcli", line 4, in <module>
    __import__('pkg_resources').run_script('ceph-iscsi==3.5', 'gwcli')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/ceph_iscsi-3.5-py3.6.egg/EGG-INFO/scripts/gwcli",
line 194, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ceph_iscsi-3.5-py3.6.egg/EGG-INFO/scripts/gwcli",
line 96, in main
  File "/usr/local/lib/python3.6/dist-packages/configshell_fb-1.1.29-py3.6.egg/configshell_fb/shell.py", line 181, in __init__
    console = console.Console()
AttributeError: 'NoneType' object has no attribute 'Console'
```

```shell
root@mgt04:~# tree ~/.gwcli
/root/.gwcli
|-- history.txt
|-- log.txt
`-- prefs.bin

0 directories, 3 files
```

## Environment

```shell
root@mgt04:~# pip3 list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
asn1crypto (0.24.0)
blinker (1.4)
ceph-iscsi (3.5)
certifi (2018.1.18)
chardet (3.0.4)
click (6.7)
colorama (0.3.7)
configshell-fb (1.1.29)
cryptography (2.1.4)
Flask (0.12.2)
idna (2.6)
itsdangerous (0.24)
Jinja2 (2.10)
keyring (10.6.0)
keyrings.alt (3.0)
MarkupSafe (1.0)
netifaces (0.10.4)
pip (9.0.1)
pycrypto (2.6.1)
pygobject (3.26.1)
pyinotify (0.9.6)
pyOpenSSL (17.5.0)
pyparsing (2.2.0)
pyudev (0.21.0)
pyxdg (0.25)
rados (2.0.0)
rbd (2.0.0)
requests (2.18.4)
rpdb (0.1.6)
rtslib-fb (2.1.74)
SecretStorage (2.3.1)
setuptools (39.0.1)
simplejson (3.13.2)
six (1.11.0)
targetcli-fb (2.1.54)
urllib3 (1.22)
urwid (2.0.1)
Werkzeug (0.14.1)
wheel (0.30.0)
root@mgt04:~#
root@mgt04:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by maurizio-lombardi** [comment]
Hello, does it work with the 1.1.29 version? In other words, is it a regression due to the latest commit?

**Comment by maurizio-lombardi** [comment]
You're absolutely right, I reverted it

**Comment by TaylorTrz** [comment]
Thanks.
